name: ghanim_law_app
description: "A new Flutter project."
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.8
  go_router: ^14.2.1
  equatable: ^2.0.5
  dartz: ^0.10.1
  dio: ^5.5.0+1
  bloc: ^8.1.4
  flutter_bloc: ^8.1.6
  shared_preferences: ^2.2.3
  get_it: ^7.7.0
  flutter_otp_text_field: ^1.1.3+2
  salomon_bottom_bar: ^3.3.2
  flutter_easyloading: ^3.0.5
  image_picker: ^1.1.2
  file_picker: ^8.0.6
  permission_handler: ^11.3.1
  path_provider: ^2.1.3
  record: ^5.1.2
  just_audio: ^0.9.39
  audio_video_progress_bar: ^2.0.3
  url_launcher: ^6.3.0
  file_downloader_flutter: ^0.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:

  uses-material-design: true
  assets:
    - assets/lang/ar.json
    - assets/lang/en.json
    - assets/images/
  fonts:
    - family: Cairo
      fonts:
        - asset: assets/fonts/Cairo/Cairo-Regular.ttf
        - asset: assets/fonts/Cairo/Cairo-Bold.ttf
          weight: 700

    - family: Rubik
      fonts:
        - asset: assets/fonts/Rubic/Rubik-Regular.ttf
        - asset: assets/fonts/Rubic/Rubik-Bold.ttf
          weight: 700
